# Generated by Django 4.1 on 2022-09-14 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('upload_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 14, 8, 12, 49, 936027, tzinfo=datetime.timezone.utc))),
                ('slug', models.SlugField(max_length=250, unique_for_date='upload_date')),
                ('isbn', models.CharField(max_length=13)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.CharField(max_length=1500)),
                ('written_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 14, 8, 12, 49, 937031, tzinfo=datetime.timezone.utc))),
                ('approved', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Pending')], default='not_approved', max_length=15)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='tusome_core.book')),
                ('review_writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-written_date',),
            },
        ),
    ]
