# Generated by Django 4.1 on 2022-09-23 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusome_core', '0002_alter_book_upload_date_alter_review_review_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='approved',
            new_name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='tusome_core.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 23, 10, 48, 52, 971487, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='written_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 23, 10, 48, 52, 971487, tzinfo=datetime.timezone.utc)),
        ),
    ]
