# Generated by Django 4.1 on 2022-09-23 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusome_core', '0003_rename_name_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 23, 14, 38, 15, 21816)),
        ),
        migrations.AlterField(
            model_name='review',
            name='written_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 23, 14, 38, 15, 22815)),
        ),
    ]
