# Generated by Django 4.1 on 2022-09-23 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusome_core', '0004_alter_book_cover_alter_book_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 14, 44, 7, 159391)),
        ),
        migrations.AlterField(
            model_name='review',
            name='written_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 14, 44, 7, 160412)),
        ),
    ]
